version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.23.0
    - 5.24.0
    - 5.24.1
    - 5.24.2
    - 5.24.3
    - 5.24.4
    - 5.25.1
    - 5.26.0
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.34.0
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: web-ext
    versions:
    - 6.0.0
    - 6.1.0
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
    - 6.0.2
  - dependency-name: copy-webpack-plugin
    versions:
    - 7.0.0
    - 8.0.0
    - 8.1.0
    - 8.1.1
  - dependency-name: webpack-cli
    versions:
    - 4.6.0
  - dependency-name: "@bamdadsabbagh/stylelint-config"
    versions:
    - 1.2.183
    - 1.2.186
    - 1.2.188
    - 1.3.0
  - dependency-name: "@bamdadsabbagh/eslint-config"
    versions:
    - 1.5.17
    - 1.7.0
    - 1.8.0
    - 1.8.2
    - 1.8.3
    - 1.9.1
  - dependency-name: wait-on
    versions:
    - 5.3.0
  - dependency-name: jspdf
    versions:
    - 2.3.0
    - 2.3.1
